// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2Gam26N2QSI2QQ-2KT2ubTrerp5oCgrE',
    appId: '1:238787717817:web:b217d57d7bf9ddea624968',
    messagingSenderId: '238787717817',
    projectId: 'final-project-flutter-34c84',
    authDomain: 'final-project-flutter-34c84.firebaseapp.com',
    storageBucket: 'final-project-flutter-34c84.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqMEdidjPreKMX3rTu94CnDxWJJSwmWuc',
    appId: '1:238787717817:android:d6a205d542e8b15c624968',
    messagingSenderId: '238787717817',
    projectId: 'final-project-flutter-34c84',
    storageBucket: 'final-project-flutter-34c84.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-OfOp9hxxg18nByhkxnQtGoLlitwe5-Y',
    appId: '1:238787717817:ios:df1ae64f6f9fb58f624968',
    messagingSenderId: '238787717817',
    projectId: 'final-project-flutter-34c84',
    storageBucket: 'final-project-flutter-34c84.appspot.com',
    iosBundleId: 'com.example.finalprojectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-OfOp9hxxg18nByhkxnQtGoLlitwe5-Y',
    appId: '1:238787717817:ios:df1ae64f6f9fb58f624968',
    messagingSenderId: '238787717817',
    projectId: 'final-project-flutter-34c84',
    storageBucket: 'final-project-flutter-34c84.appspot.com',
    iosBundleId: 'com.example.finalprojectflutter',
  );
}
